<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>MusicUser</RootNamespace>
        <UserSecretsId>cd1c57e5-dd02-4402-b906-2fb212688eed</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.11" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.17" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.17">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="9.0.0" />
        <PackageReference Include="Microsoft.Extensions.Resilience" Version="9.0.0" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="9.0.17" />
        <PackageReference Include="Npgsql" Version="9.0.4" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
        <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
        <PackageReference Include="Utility.Kafka.2025" Version="2.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Music.User.Business\Music.User.Business.csproj" />
    </ItemGroup>

</Project>