<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Music.User.Shared\Music.User.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="music.catalogue.clienthttp" Version="1.0.10" />
      <PackageReference Include="music.catalogue.shared" Version="1.0.6" />
      <PackageReference Include="Music.Library.ClientHttp" Version="1.0.8" />
      <PackageReference Include="Music.Library.Shared" Version="1.0.3" />
    </ItemGroup>

</Project>
